package xapp

import (
	"net/http"
	"net/http/httptest"
	"os"
	"reflect"
	"strings"
	"testing"

	"github.com/gin-gonic/gin"
)

type docAPITestReq struct {
	DisplayName string `json:"display_name"`
}

type docAPITestResp struct {
	DisplayName string `json:"display_name"`
	AvatarURL   string `json:"avatar_url"`
}

// docAPITestController mimics the common project style: handlers are methods
// that own binding and rendering themselves.
type docAPITestController struct{}

// @summary 方法源码注释
// @tags method-comment
func (d *docAPITestController) UpdateProfile(c *gin.Context) {
	// Deliberately NOT the xapp envelope: RegisterAPIDoc must never touch rendering.
	c.String(http.StatusTeapot, "raw-body")
}

type docAPIValueRecvController struct{}

// @summary 值接收者方法注释
func (d docAPIValueRecvController) Ping(c *gin.Context) {
	c.Status(http.StatusOK)
}

// @summary plain function summary
// @tags demo
func docAPITestPlainHandler(c *gin.Context) {
	c.Status(http.StatusNoContent)
}

// withOpenAPIEnabled flips Args.EnableOpenAPI and isolates apiRegistry for one test.
func withOpenAPIEnabled(t *testing.T) {
	t.Helper()
	prevEnabled := Args.EnableOpenAPI
	prevRegistry := apiRegistry
	Args.EnableOpenAPI = true
	apiRegistry = nil
	t.Cleanup(func() {
		Args.EnableOpenAPI = prevEnabled
		apiRegistry = prevRegistry
	})
}

// RegisterAPIDoc is a pure registration core: EnableOpenAPI / go-run gating is
// the caller's concern (RegisterAPI or a project-defined wrapper), so the core
// must register even with the flag off.
func TestRegisterAPIDoc_NoGatesInsideCore(t *testing.T) {
	prevEnabled := Args.EnableOpenAPI
	prevRegistry := apiRegistry
	Args.EnableOpenAPI = false
	apiRegistry = nil
	t.Cleanup(func() {
		Args.EnableOpenAPI = prevEnabled
		apiRegistry = prevRegistry
	})

	if !RegisterAPIDoc[docAPITestReq, docAPITestResp](docAPITestPlainHandler, docAPITestPlainHandler) {
		t.Fatal("core must register regardless of EnableOpenAPI")
	}
	if len(apiRegistry) != 1 {
		t.Fatalf("expected 1 registry entry, got %d", len(apiRegistry))
	}
}

// A project-defined wrapper: comments come from the source method, while the
// route (and registry Handler) carry the wrapped closure. Route matching must
// pair by the wrapped handler's pointer, and rendering stays fully custom.
func TestRegisterAPIDoc_CustomWrapMatchesRoute(t *testing.T) {
	withOpenAPIEnabled(t)

	gin.SetMode(gin.TestMode)
	ctrl := &docAPITestController{}
	wrapped := gin.HandlerFunc(func(c *gin.Context) { ctrl.UpdateProfile(c) })
	if !RegisterAPIDoc[docAPITestReq, docAPITestResp](ctrl.UpdateProfile, wrapped) {
		t.Fatal("RegisterAPIDoc must report true on success")
	}
	engine := gin.New()
	engine.PATCH("/im/me/profile", wrapped)

	CollectRouteInfo(engine)

	if len(apiRegistry) != 1 {
		t.Fatalf("expected 1 registry entry, got %d", len(apiRegistry))
	}
	info := apiRegistry[0]
	if info.Path != "/im/me/profile" || info.Method != "PATCH" {
		t.Fatalf("route matching failed: path=%q method=%q", info.Path, info.Method)
	}
	if info.Summary != "方法源码注释" {
		t.Fatalf("summary must come from the source method, got %q", info.Summary)
	}
	if info.RequestType != reflect.TypeOf(docAPITestReq{}) {
		t.Fatalf("unexpected request type %v", info.RequestType)
	}
	if info.ResponseType != reflect.TypeOf(docAPITestResp{}) {
		t.Fatalf("unexpected response type %v", info.ResponseType)
	}

	// Runtime behavior must be exactly the wrapped handler's own rendering.
	w := httptest.NewRecorder()
	req := httptest.NewRequest(http.MethodPatch, "/im/me/profile", nil)
	engine.ServeHTTP(w, req)
	if w.Code != http.StatusTeapot || w.Body.String() != "raw-body" {
		t.Fatalf("handler behavior changed: code=%d body=%q", w.Code, w.Body.String())
	}
}

// Method values are attributed to <autogenerated> by the runtime, so FileLine
// is useless — but the wrapper symbol name (pkg.(*T).Method-fm) still identifies
// the real method, whose doc comment must be recovered from source via AST.
func TestRegisterAPIDoc_MethodValueSourceComment(t *testing.T) {
	withOpenAPIEnabled(t)

	ctrl := &docAPITestController{}
	handler := gin.HandlerFunc(ctrl.UpdateProfile)
	RegisterAPIDoc[docAPITestReq, docAPITestResp](handler, handler)

	if len(apiRegistry) != 1 {
		t.Fatalf("expected 1 registry entry, got %d", len(apiRegistry))
	}
	info := apiRegistry[0]
	if info.Summary != "方法源码注释" {
		t.Fatalf("pointer-receiver method comment not extracted, got %q", info.Summary)
	}
	if len(info.Tags) != 1 || info.Tags[0] != "method-comment" {
		t.Fatalf("method comment tags not extracted, got %v", info.Tags)
	}
}

func TestRegisterAPIDoc_ValueReceiverMethodSourceComment(t *testing.T) {
	withOpenAPIEnabled(t)

	handler := gin.HandlerFunc(docAPIValueRecvController{}.Ping)
	RegisterAPIDoc[docAPITestReq, docAPITestResp](handler, handler)

	if len(apiRegistry) != 1 {
		t.Fatalf("expected 1 registry entry, got %d", len(apiRegistry))
	}
	if apiRegistry[0].Summary != "值接收者方法注释" {
		t.Fatalf("value-receiver method comment not extracted, got %q", apiRegistry[0].Summary)
	}
}

// Aligned with RegisterAPI: when the handler source cannot be resolved at all
// (here: method value with CWD outside the module, so the package dir lookup
// fails), the entry is skipped instead of being registered with empty metadata.
func TestRegisterAPIDoc_SkipsWhenCommentExtractionFails(t *testing.T) {
	withOpenAPIEnabled(t)

	wd, err := os.Getwd()
	if err != nil {
		t.Fatal(err)
	}
	if err := os.Chdir(t.TempDir()); err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() {
		if err := os.Chdir(wd); err != nil {
			t.Fatal(err)
		}
	})

	ctrl := &docAPITestController{}
	handler := gin.HandlerFunc(ctrl.UpdateProfile)
	if RegisterAPIDoc[docAPITestReq, docAPITestResp](handler, handler) {
		t.Fatal("RegisterAPIDoc must report false when the source cannot be resolved")
	}
	if len(apiRegistry) != 0 {
		t.Fatalf("unresolvable handler source must skip registration, got %d entries", len(apiRegistry))
	}
}

// Plain functions keep the RegisterAPI behavior: comments above the function
// definition are extracted.
func TestRegisterAPIDoc_PlainFunctionSourceComment(t *testing.T) {
	withOpenAPIEnabled(t)

	RegisterAPIDoc[docAPITestReq, docAPITestResp](docAPITestPlainHandler, docAPITestPlainHandler)

	if len(apiRegistry) != 1 {
		t.Fatalf("expected 1 registry entry, got %d", len(apiRegistry))
	}
	info := apiRegistry[0]
	if info.Summary != "plain function summary" {
		t.Fatalf("source comment summary not extracted, got %q", info.Summary)
	}
	if len(info.Tags) != 1 || info.Tags[0] != "demo" {
		t.Fatalf("source comment tags not extracted, got %v", info.Tags)
	}
}

// End-to-end through genDoc: a RegisterAPIDoc-annotated route produces an
// operation with path params from the route pattern and the request body schema
// for PATCH.
func TestRegisterAPIDoc_GenDoc(t *testing.T) {
	withOpenAPIEnabled(t)

	gin.SetMode(gin.TestMode)
	ctrl := &docAPITestController{}
	handler := gin.HandlerFunc(ctrl.UpdateProfile)
	RegisterAPIDoc[docAPITestReq, docAPITestResp](handler, handler)
	engine := gin.New()
	engine.PATCH("/im/channels/:channel_id/profile", handler)

	doc, err := genDoc(engine, WithInfo("t", "1.0.0", "d"))
	if err != nil {
		t.Fatalf("genDoc: %v", err)
	}
	item, ok := doc.Paths["/im/channels/{channel_id}/profile"]
	if !ok {
		keys := make([]string, 0, len(doc.Paths))
		for k := range doc.Paths {
			keys = append(keys, k)
		}
		t.Fatalf("path not found in doc, have: %s", strings.Join(keys, ", "))
	}
	if item.Patch == nil {
		t.Fatal("PATCH operation missing")
	}
	var hasPathParam bool
	for _, p := range item.Patch.Parameters {
		if p.In == "path" && p.Name == "channel_id" {
			hasPathParam = true
		}
	}
	if !hasPathParam {
		t.Fatal("path parameter channel_id missing")
	}
	if item.Patch.RequestBody == nil {
		t.Fatal("request body missing for PATCH")
	}
}
